# Generated by Django 6.0.3 on 2026-03-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=600)),
                ('init_bet', models.PositiveIntegerField()),
                ('img_url', models.URLField(verbose_name='?')),
            ],
        ),
    ]
