# Generated by Django 6.0.3 on 2026-03-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
